name: KwarChart CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_test:
    name: Building and testing
    runs-on: ubuntu-latest

    steps:
    # Checks out a repository copy on the "runs-on" machine
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Setup JDK
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Unit Test with Gradle
      run: ./gradlew kwarchart:test

    - name: Instrumented Test with Gradle
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: ./gradlew connectedCheck